/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacejava;

import classedados.Calculadora;
import classedados.Validacao;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaPincipal extends javax.swing.JFrame {

    //Instancia
    Calculadora calc = new Calculadora();
    
    public TelaPincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEntrada1 = new javax.swing.JTextField();
        jTextFieldEntrada2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonDivisao = new javax.swing.JButton();
        jButtonAdicao = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonPotencia = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        jTextFieldSaida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Calculadora");
        setLocation(new java.awt.Point(600, 350));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PROGRAMA DA CLASSE");

        jTextFieldEntrada1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldEntrada1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEntrada1KeyTyped(evt);
            }
        });

        jTextFieldEntrada2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldEntrada2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEntrada2KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("CALCULADORA");

        jButtonDivisao.setBackground(java.awt.Color.blue);
        jButtonDivisao.setForeground(java.awt.Color.blue);
        jButtonDivisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Divisao.jpg"))); // NOI18N
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButtonAdicao.setBackground(java.awt.Color.blue);
        jButtonAdicao.setForeground(java.awt.Color.blue);
        jButtonAdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Adicao.jpg"))); // NOI18N
        jButtonAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicaoActionPerformed(evt);
            }
        });

        jButtonMultiplicacao.setBackground(java.awt.Color.blue);
        jButtonMultiplicacao.setForeground(java.awt.Color.blue);
        jButtonMultiplicacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Multiplicacao.jpg"))); // NOI18N
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonPotencia.setBackground(java.awt.Color.blue);
        jButtonPotencia.setForeground(java.awt.Color.blue);
        jButtonPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Potencia.jpg"))); // NOI18N
        jButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciaActionPerformed(evt);
            }
        });

        jButtonSubtracao.setBackground(java.awt.Color.blue);
        jButtonSubtracao.setForeground(java.awt.Color.blue);
        jButtonSubtracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Subtracao.jpg"))); // NOI18N
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });

        jButtonRaiz.setBackground(java.awt.Color.blue);
        jButtonRaiz.setForeground(java.awt.Color.blue);
        jButtonRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Raiz.jpg"))); // NOI18N
        jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizActionPerformed(evt);
            }
        });

        jTextFieldSaida.setEditable(false);
        jTextFieldSaida.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSaida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAdicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDivisao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonPotencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRaiz)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSubtracao)
                            .addComponent(jButtonMultiplicacao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdicao)
                            .addComponent(jButtonDivisao)
                            .addComponent(jButtonMultiplicacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSubtracao)
                            .addComponent(jButtonRaiz)))
                    .addComponent(jButtonPotencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicaoActionPerformed
        if(!(jTextFieldEntrada1.getText().equals("")||jTextFieldEntrada2.getText().equals(""))){
            try {
                calc.setNumero1(Float.parseFloat(jTextFieldEntrada1.getText()));
                calc.setNumero2(Float.parseFloat(jTextFieldEntrada2.getText()));
                jTextFieldSaida.setText(calc.adicao()+"");
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(rootPane, "Permitido apenas um '.' e/ou um '-' .");
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Não permitido campo vazio. ");
    }//GEN-LAST:event_jButtonAdicaoActionPerformed

    private void jTextFieldEntrada1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEntrada1KeyTyped
        try {
            if(jTextFieldEntrada1.getText().length()>=9){
                evt.consume();
            }
            Validacao x = new Validacao();
        if(!x.validaCampoNumero(String.valueOf(evt.getKeyChar()))){
            evt.consume();
        }
            
        } catch (Exception e) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEntrada1KeyTyped

    private void jTextFieldEntrada2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEntrada2KeyTyped
        try {
            if(jTextFieldEntrada2.getText().length()>=9){
                evt.consume();
            }
            Validacao x = new Validacao();
        if(!x.validaCampoNumero(String.valueOf(evt.getKeyChar()))){
            evt.consume();
        }
            
        } catch (Exception e) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEntrada2KeyTyped

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
        if(!(jTextFieldEntrada1.getText().equals("")||jTextFieldEntrada2.getText().equals(""))){
            try {
                calc.setNumero1(Float.parseFloat(jTextFieldEntrada1.getText()));
                calc.setNumero2(Float.parseFloat(jTextFieldEntrada2.getText()));
                jTextFieldSaida.setText(calc.divisao()+"");
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(rootPane, "Permitido apenas um '.' e/ou um '-' .");
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Não permitido campo vazio. ");
    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        if(!(jTextFieldEntrada1.getText().equals("")||jTextFieldEntrada2.getText().equals(""))){
            try {
                calc.setNumero1(Float.parseFloat(jTextFieldEntrada1.getText()));
                calc.setNumero2(Float.parseFloat(jTextFieldEntrada2.getText()));
                jTextFieldSaida.setText(calc.multiplicacao()+"");
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(rootPane, "Permitido apenas um '.' e/ou um '-' .");
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Não permitido campo vazio. ");
    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciaActionPerformed
        if(!(jTextFieldEntrada1.getText().equals("")||jTextFieldEntrada2.getText().equals(""))){
            try {
                calc.setNumero1(Float.parseFloat(jTextFieldEntrada1.getText()));
                calc.setNumero2(Float.parseFloat(jTextFieldEntrada2.getText()));
                jTextFieldSaida.setText(calc.caucularPotencia()+"");
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(rootPane, "Permitido apenas um '.' e/ou um '-' .");
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Não permitido campo vazio. ");
    }//GEN-LAST:event_jButtonPotenciaActionPerformed

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
        if(!(jTextFieldEntrada1.getText().equals("")||jTextFieldEntrada2.getText().equals(""))){
            try {
                calc.setNumero1(Float.parseFloat(jTextFieldEntrada1.getText()));
                calc.setNumero2(Float.parseFloat(jTextFieldEntrada2.getText()));
                jTextFieldSaida.setText(calc.caucularRaiz()+"");
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(rootPane, "Permitido apenas um '.' e/ou um '-' .");
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Não permitido campo vazio. ");
    }//GEN-LAST:event_jButtonRaizActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed
        if(!(jTextFieldEntrada1.getText().equals("")||jTextFieldEntrada2.getText().equals(""))){
            try {
                calc.setNumero1(Float.parseFloat(jTextFieldEntrada1.getText()));
                calc.setNumero2(Float.parseFloat(jTextFieldEntrada2.getText()));
                jTextFieldSaida.setText(calc.subtracao()+"");
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(rootPane, "Permitido apenas um '.' e/ou um '-' .");
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Não permitido campo vazio. ");
    }//GEN-LAST:event_jButtonSubtracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicao;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonPotencia;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEntrada1;
    private javax.swing.JTextField jTextFieldEntrada2;
    private javax.swing.JTextField jTextFieldSaida;
    // End of variables declaration//GEN-END:variables
}
